project:
  type: website
  output-dir: docs

website:
  title: "Mi proyecto"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - visualizing_distributions.qmd
      - eda.qmd
      - geo.qmd

format:
  html:
    theme: cosmo
    toc: true

code-fold: true

execute:
  freeze: auto